// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hj;

import hj.Country;

privileged aspect Country_Roo_History {
    
    String Country.sampleField;
    
    public void Country.sampleMethod() {
        System.out.println("Hello World");
    }
    
}
