// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hj;

import hj.Country;
import hj.CountryHistory;
import java.util.List;

privileged aspect Country_Roo_History {
    
    public List<CountryHistory> Country.getHistory() {
        return CountryHistory.findCountryHistorysByCountryIdEquals(getId()).getResultList();
    }
    
}
