// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hj;

import hj.CountryHistory;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CountryHistory_Roo_Configurable {
    
    declare @type: CountryHistory: @Configurable;
    
}
