// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hj;

import hj.CountryHistory;

privileged aspect CountryHistory_Roo_JavaBean {
    
    public String CountryHistory.getTest() {
        return this.test;
    }
    
    public void CountryHistory.setTest(String test) {
        this.test = test;
    }
    
}
